import { Head, router, useForm } from '@inertiajs/react';
import { Store } from 'lucide-react';
import AdminLayout from '@/Layouts/AdminLayout';
import { Button, Card, Input, Select, Textarea } from '@/Components/ui';

export default function Branding({ workspace, workspaces, profile, outlets }) {
    const form = useForm({ brand_name: profile.brand_name ?? '', primary_color: profile.primary_color ?? '', thank_you_note: profile.thank_you_note ?? '', social_links: profile.social_links ?? {}, logo: null, cover: null });
    const submit = (event) => { event.preventDefault(); if (workspace) form.put(route('admin.restaurant.branding.update', workspace.id), { forceFormData: true, preserveScroll: true }); };
    return <AdminLayout><Head title="Restaurant Branding" /><div className="mb-6"><div className="flex items-center gap-2"><Store className="h-5 w-5 text-brand-600" /><h1 className="text-xl font-semibold">Restaurant Branding</h1></div><p className="mt-1 text-sm text-neutral-500">Public digital-bill identity only. Saving does not send any message.</p></div>
        <Card><Select label="Workspace / restaurant" value={workspace?.id ?? ''} options={[{ value: '', label: 'Select a workspace' }, ...workspaces.map((item) => ({ value: item.id, label: item.name }))]} onChange={(e) => router.get(route('admin.restaurant.branding.index'), { workspace_id: e.target.value || undefined })} /></Card>
        {workspace && <form className="mt-5 space-y-5" onSubmit={submit}><Card><div className="grid gap-4 md:grid-cols-2"><Input label="Brand name" value={form.data.brand_name} onChange={(e) => form.setData('brand_name', e.target.value)} error={form.errors.brand_name} /><Input label="Primary color" placeholder="#1f2937" value={form.data.primary_color} onChange={(e) => form.setData('primary_color', e.target.value)} error={form.errors.primary_color} /><Input label="Logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => form.setData('logo', e.target.files?.[0] ?? null)} /><Input label="Cover image" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => form.setData('cover', e.target.files?.[0] ?? null)} /><Textarea className="md:col-span-2" label="Thank-you note" value={form.data.thank_you_note} onChange={(e) => form.setData('thank_you_note', e.target.value)} />{['instagram', 'facebook', 'x', 'youtube'].map((key) => <Input key={key} label={`${key[0].toUpperCase()}${key.slice(1)} URL`} type="url" value={form.data.social_links[key] ?? ''} onChange={(e) => form.setData('social_links', { ...form.data.social_links, [key]: e.target.value })} />)}</div><div className="mt-5 flex justify-end"><Button type="submit" disabled={form.processing}>Save branding</Button></div></Card></form>}
        {workspace && <div className="mt-5 space-y-4">{outlets.map((outlet) => <OutletContact key={outlet.uuid} workspace={workspace} outlet={outlet} />)}</div>}
    </AdminLayout>;
}

function OutletContact({ workspace, outlet }) { const form = useForm({ public_phone: outlet.public_phone ?? '', public_website: outlet.public_website ?? '' }); return <Card><form onSubmit={(event) => { event.preventDefault(); form.put(route('admin.restaurant.branding.outlets.update', [workspace.id, outlet.uuid]), { preserveScroll: true }); }}><h2 className="font-medium">{outlet.name}</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Input label="Public phone" value={form.data.public_phone} onChange={(e) => form.setData('public_phone', e.target.value)} /><Input label="Public website" type="url" value={form.data.public_website} onChange={(e) => form.setData('public_website', e.target.value)} /></div><div className="mt-4 flex justify-end"><Button type="submit" variant="secondary" disabled={form.processing}>Save outlet details</Button></div></form></Card>; }
