import { Head, useForm } from '@inertiajs/react';
import { Building2, CreditCard, MapPin, MessageSquare } from 'lucide-react';
import ClientLayout from '@/Layouts/ClientLayout';
import { Badge, Button, Card, Input, Textarea } from '@/Components/ui';

const timingLabels = { immediately: 'Immediately', one_hour: '1 hour later', five_hours: '5 hours later', next_day: 'Next day at a chosen local time', seven_days: '7 days later' };

export default function ProfileMessaging({ profile, outlets, digitalBillDeliveryOptions, feedbackDeliveryOptions, feedbackTimingPreferences }) {
    return <ClientLayout title="Restaurant Profile & Messaging"><Head title="Restaurant Profile & Messaging" />
        <header className="mb-6"><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-brand-600" /><h1 className="text-xl font-semibold">Restaurant Profile &amp; Messaging</h1></div><p className="mt-1 max-w-3xl text-sm text-neutral-500">Manage your shared restaurant identity and each outlet’s future Digital Bill and Feedback settings. Saving configuration never sends a message.</p></header>
        <BrandProfile profile={profile} />
        <section className="mt-8"><div className="mb-3 flex items-center gap-2"><MapPin className="h-4 w-4" /><h2 className="text-lg font-semibold">Outlet &amp; Billing Details</h2></div><div className="space-y-5">{outlets.map((outlet) => <OutletCard key={outlet.uuid} outlet={outlet} digitalOptions={digitalBillDeliveryOptions} feedbackOptions={feedbackDeliveryOptions} timingPreferences={feedbackTimingPreferences} />)}{outlets.length === 0 && <Card><p className="py-4 text-center text-sm text-neutral-500">No outlets are available in this workspace.</p></Card>}</div></section>
    </ClientLayout>;
}

function BrandProfile({ profile }) {
    const form = useForm({ brand_name: profile.brand_name ?? '', legal_business_name: profile.legal_business_name ?? '', registered_business_address: profile.registered_business_address ?? '', primary_color: profile.primary_color ?? '', thank_you_note: profile.thank_you_note ?? '', website: profile.website ?? '', social_links: profile.social_links ?? {}, logo: null, cover: null, _method: 'put' });
    const submit = (e) => { e.preventDefault(); form.post(route('client.restaurant.profile-messaging.profile.update'), { forceFormData: true, preserveScroll: true }); };
    return <section><div className="mb-3 flex items-center gap-2"><Building2 className="h-4 w-4" /><h2 className="text-lg font-semibold">Business &amp; Brand Profile</h2></div><form onSubmit={submit}><Card><p className="mb-4 text-sm text-neutral-500">Used for your restaurant profile and public Digital Bill presentation. Leave the thank-you note blank to omit it from public bills.</p><div className="grid gap-4 md:grid-cols-2"><Input label="Brand / display name" value={form.data.brand_name} onChange={(e) => form.setData('brand_name', e.target.value)} error={form.errors.brand_name} /><Input label="Legal business name" value={form.data.legal_business_name} onChange={(e) => form.setData('legal_business_name', e.target.value)} error={form.errors.legal_business_name} /><Textarea className="md:col-span-2" label="Registered business address" value={form.data.registered_business_address} onChange={(e) => form.setData('registered_business_address', e.target.value)} error={form.errors.registered_business_address} /><Input label="Website" type="url" value={form.data.website} onChange={(e) => form.setData('website', e.target.value)} error={form.errors.website} /><Input label="Primary color" placeholder="#1f2937" value={form.data.primary_color} onChange={(e) => form.setData('primary_color', e.target.value)} error={form.errors.primary_color} /><Input label="Logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => form.setData('logo', e.target.files?.[0] ?? null)} error={form.errors.logo} /><Input label="Digital Bill banner / cover" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => form.setData('cover', e.target.files?.[0] ?? null)} error={form.errors.cover} /><Textarea className="md:col-span-2" label="Thank-you note" value={form.data.thank_you_note} onChange={(e) => form.setData('thank_you_note', e.target.value)} error={form.errors.thank_you_note} />{['instagram', 'facebook', 'google', 'youtube'].map((key) => <Input key={key} label={`${key[0].toUpperCase()}${key.slice(1)} URL`} type="url" value={form.data.social_links[key] ?? ''} onChange={(e) => form.setData('social_links', { ...form.data.social_links, [key]: e.target.value })} error={form.errors[`social_links.${key}`]} />)}</div><div className="mt-5 flex justify-end"><Button type="submit" disabled={form.processing}>Save business profile</Button></div></Card></form></section>;
}

function OutletCard({ outlet, digitalOptions, feedbackOptions, timingPreferences }) {
    return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{outlet.name}</h3><p className="mt-1 text-xs text-neutral-500">Each outlet keeps independent billing, sender, template, and feedback preferences.</p></div><Badge variant="default" size="sm">{outlet.status}</Badge></div><OutletDetails outlet={outlet} /><MessagingToggle outlet={outlet} /><DeliveryConfig title="Digital Bill configuration" outlet={outlet} options={digitalOptions} config={outlet.digital_bill_delivery_config} routeName="client.restaurant.profile-messaging.outlets.digital-bill.update" utilityOnly /><FeedbackConfig outlet={outlet} options={feedbackOptions} config={outlet.feedback_delivery_config} timingPreferences={timingPreferences} /></Card>;
}

function OutletDetails({ outlet }) {
    const form = useForm({ name: outlet.name ?? '', address: outlet.address ?? '', public_phone: outlet.public_phone ?? '', public_email: outlet.public_email ?? '', public_website: outlet.public_website ?? '', gstin: outlet.gstin ?? '', fssai_number: outlet.fssai_number ?? '' });
    return <form onSubmit={(e) => { e.preventDefault(); form.put(route('client.restaurant.profile-messaging.outlets.update', outlet.uuid), { preserveScroll: true }); }} className="mt-5 border-t pt-4"><h4 className="text-sm font-semibold">Outlet &amp; billing details</h4><div className="mt-3 grid gap-3 md:grid-cols-2"><Input label="Outlet name" value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} error={form.errors.name} /><Input label="Contact phone" value={form.data.public_phone} onChange={(e) => form.setData('public_phone', e.target.value)} error={form.errors.public_phone} /><Textarea className="md:col-span-2" label="Outlet / billing address" value={form.data.address} onChange={(e) => form.setData('address', e.target.value)} error={form.errors.address} /><Input label="Contact email" type="email" value={form.data.public_email} onChange={(e) => form.setData('public_email', e.target.value)} error={form.errors.public_email} /><Input label="Website override" type="url" value={form.data.public_website} onChange={(e) => form.setData('public_website', e.target.value)} error={form.errors.public_website} /><Input label="GSTIN" value={form.data.gstin} onChange={(e) => form.setData('gstin', e.target.value.toUpperCase())} error={form.errors.gstin} /><Input label="FSSAI number" inputMode="numeric" value={form.data.fssai_number} onChange={(e) => form.setData('fssai_number', e.target.value)} error={form.errors.fssai_number} /></div><div className="mt-3 flex justify-end"><Button type="submit" variant="secondary" disabled={form.processing}>Save outlet details</Button></div></form>;
}

function MessagingToggle({ outlet }) {
    const form = useForm({ digital_bill_enabled: Boolean(outlet.digital_bill_enabled), feedback_request_enabled: Boolean(outlet.feedback_request_enabled) });
    return <form onSubmit={(e) => { e.preventDefault(); form.put(route('client.restaurant.profile-messaging.outlets.messaging.update', outlet.uuid), { preserveScroll: true }); }} className="mt-5 border-t pt-4"><h4 className="text-sm font-semibold">Messaging settings</h4><p className="mt-1 text-xs text-neutral-500">Both controls affect only future behavior. Changing them does not send anything.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><Toggle id={`digital-${outlet.uuid}`} label="Digital Bill" description="Controls future Digital Bill delivery only." checked={form.data.digital_bill_enabled} onChange={(value) => form.setData('digital_bill_enabled', value)} /><Toggle id={`feedback-${outlet.uuid}`} label="Feedback request" description="Controls future Feedback behavior only." checked={form.data.feedback_request_enabled} onChange={(value) => form.setData('feedback_request_enabled', value)} /></div><div className="mt-3 flex justify-end"><Button type="submit" variant="secondary" disabled={form.processing}>Save messaging settings</Button></div></form>;
}

function DeliveryConfig({ title, outlet, options, config, routeName, utilityOnly }) {
    const form = useForm({ whatsapp_phone_number_id: config?.whatsapp_phone_number_id ?? '', whatsapp_template_id: config?.whatsapp_template_id ?? '' });
    const sender = options?.senders?.find((item) => Number(item.id) === Number(form.data.whatsapp_phone_number_id));
    return <form onSubmit={(e) => { e.preventDefault(); form.put(route(routeName, outlet.uuid), { preserveScroll: true }); }} className="mt-5 border-t pt-4"><div className="flex items-center gap-2"><CreditCard className="h-4 w-4" /><h4 className="text-sm font-semibold">{title}</h4></div><p className="mt-1 text-xs text-neutral-500">Configuration is revalidated before any future delivery.{utilityOnly ? ' Select an approved Utility template with a dynamic bill-link URL button for future delivery.' : ''}</p><div className="mt-3 grid gap-3 md:grid-cols-2"><Select label="WhatsApp sender" value={form.data.whatsapp_phone_number_id} onChange={(value) => { form.setData('whatsapp_phone_number_id', value); form.setData('whatsapp_template_id', ''); }} items={options?.senders ?? []} empty="Select a sender" /><Select label={utilityOnly ? 'Approved Utility template' : 'Approved feedback template'} value={form.data.whatsapp_template_id} onChange={(value) => form.setData('whatsapp_template_id', value)} items={sender?.templates ?? []} empty={sender ? 'Select a template' : 'Select a sender first'} disabled={!sender} /></div>{(form.errors.whatsapp_phone_number_id || form.errors.whatsapp_template_id) && <p className="mt-2 text-sm text-coral-600">{form.errors.whatsapp_phone_number_id || form.errors.whatsapp_template_id}</p>}<div className="mt-3 flex justify-end"><Button type="submit" variant="secondary" disabled={form.processing}>Save configuration</Button></div></form>;
}

function FeedbackConfig({ outlet, options, config, timingPreferences }) {
    const form = useForm({ whatsapp_phone_number_id: config?.whatsapp_phone_number_id ?? '', whatsapp_template_id: config?.whatsapp_template_id ?? '', timing_preference: config?.timing_preference ?? 'immediately', next_day_at: config?.next_day_at ?? '', google_review_url: config?.google_review_url ?? '' });
    const sender = options?.senders?.find((item) => Number(item.id) === Number(form.data.whatsapp_phone_number_id));
    return <form onSubmit={(e) => { e.preventDefault(); form.put(route('client.restaurant.profile-messaging.outlets.feedback.update', outlet.uuid), { preserveScroll: true }); }} className="mt-5 border-t pt-4"><div className="flex items-center gap-2"><MessageSquare className="h-4 w-4" /><h4 className="text-sm font-semibold">Feedback automation configuration</h4></div><p className="mt-1 text-xs text-neutral-500">This stores preferences only. No feedback message is sent from this page.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><Select label="WhatsApp sender" value={form.data.whatsapp_phone_number_id} onChange={(value) => { form.setData('whatsapp_phone_number_id', value); form.setData('whatsapp_template_id', ''); }} items={options?.senders ?? []} empty="Select a sender" /><Select label="Approved feedback template" value={form.data.whatsapp_template_id} onChange={(value) => form.setData('whatsapp_template_id', value)} items={sender?.templates ?? []} empty={sender ? 'Select a template' : 'Select a sender first'} disabled={!sender} /><label className="text-sm font-medium">Timing preference<select value={form.data.timing_preference} onChange={(e) => form.setData('timing_preference', e.target.value)} className="mt-1 block w-full rounded-soft border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-900">{timingPreferences.map((value) => <option key={value} value={value}>{timingLabels[value]}</option>)}</select></label>{form.data.timing_preference === 'next_day' && <Input label="Next-day local time" type="time" value={form.data.next_day_at} onChange={(e) => form.setData('next_day_at', e.target.value)} error={form.errors.next_day_at} />}<Input className="md:col-span-2" label="Google review URL (optional)" type="url" value={form.data.google_review_url} onChange={(e) => form.setData('google_review_url', e.target.value)} error={form.errors.google_review_url} /></div>{(form.errors.whatsapp_phone_number_id || form.errors.whatsapp_template_id || form.errors.timing_preference) && <p className="mt-2 text-sm text-coral-600">{form.errors.whatsapp_phone_number_id || form.errors.whatsapp_template_id || form.errors.timing_preference}</p>}<div className="mt-3 flex justify-end"><Button type="submit" variant="secondary" disabled={form.processing}>Save feedback configuration</Button></div></form>;
}

function Select({ label, value, onChange, items, empty, disabled = false }) { return <label className="text-sm font-medium">{label}<select value={value} disabled={disabled} onChange={(e) => onChange(e.target.value)} className="mt-1 block w-full rounded-soft border-neutral-300 text-sm disabled:opacity-60 dark:border-neutral-700 dark:bg-neutral-900"><option value="">{empty}</option>{items.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>; }
function Toggle({ id, label, description, checked, onChange }) { return <label htmlFor={id} className="flex cursor-pointer items-start gap-3 rounded-soft border border-neutral-200 p-3 dark:border-neutral-700"><input id={id} type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="mt-1 h-4 w-4 rounded border-neutral-300 text-brand-600 focus:ring-brand-500" /><span><span className="block text-sm font-medium">{label}</span><span className="mt-0.5 block text-xs text-neutral-500">{description}</span></span></label>; }
